### ISSUE TITLE
peerDependencies in npm 3+

### ISSUE THREAD

**Issue by vbulant** [actum/generator-actum-frontend#2]
**npm WARN peerDependencies** The peer dependency browserify@>= 2.3.0 < 11 included from browserify-shim will no longer be automatically installed to fulfill the peerDependency in npm 3+. Your application will need to depend on it explicitly.

**npm ERR! peerinvalid** The package browserify does not satisfy its siblings' peerDependencies requirements! Peer browserify-shim@3.8.9 wants browserify@>= 2.3.0 < 11

**Comment by vbulant** [comment]
browserify-shim needs browserify < 11 as a peerDependency. But browserify is already a version 11. So after "npm install", browserify-shim's peerDependencies fail.

I'd suggest that we'll wait until browserify-shim's peerDependencies gets an update.

Anyway, this can be solved manually after failed npm install.

**Comment by vbulant** [comment]
Resolved by browserify-shim@3.8.10

**Comment by janpanschab** [comment]
:+1:
